substitutions:
  name: co2sensor

esphome:
  name: $name

esp8266:
  board: d1_mini

logger:

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

web_server:
  ota: false
  local: true

prometheus:

i2c:

sensor:
  - platform: scd4x
    co2:
      name: CO2
    temperature:
      name: Temperature
    humidity:
      name: Humidity
    measurement_mode: low_power_periodic
