{
 "title": "CO2 Sensors",
 "description": "CO2, temperature, humidity",
 "tags": [
  "esphome",
  "co2"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "CO2",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "expr": "esphome_sensor_value{id=\"co2\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "esphome_sensor_value{id=\"temperature\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "expr": "esphome_sensor_value{id=\"humidity\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}